// Número de WhatsApp da loja (55 + DDD + número)
const WHATSAPP_NUMBER = "5511952854008";

// Aqui você cadastra TODOS os produtos
const PRODUCTS = {
  "dunk-panda": {
    slug: "dunk-panda",
    name: "NK Dunk Low “Panda”",
    brand: "Nike",
    gender: "Unissex",
    category: "Casual / Lifestyle",
    price: "R$ 299,00",
    sizes: ["37", "38", "39", "40", "41", "42"],
    badgeMain: "Frete grátis acima de R$ 299",
    badgeSecondary: "Estoque limitado",
    description:
      "O NK Dunk Low “Panda” é o clássico preto e branco que combina com tudo. Cabedal em material sintético, acabamento clean e sola emborrachada para aguentar o uso no dia a dia, da rua ao rolê.",
    highlights: [
      "Visual preto e branco fácil de combinar",
      "Silhueta baixa inspirada no basquete",
      "Palminha confortável para uso prolongado",
      "Perfeito para quem curte estética streetwear"
    ],
    mainImageLabel: "FOTO PRINCIPAL DUNK LOW PANDA",
    thumbs: ["Lateral", "Traseira", "Solado", "Detalhe"],
    whatsappText:
      "Ol%C3%A1,%20tenho%20interesse%20no%20NK%20Dunk%20Low%20Panda.%20Voc%C3%AAs%20t%C3%AAm%20no%20tamanho%20(37-42)%3F"
  },

  "campus-all-black": {
    slug: "campus-all-black",
    name: "ADDS Campus All Black",
    brand: "Adidas",
    gender: "Masculino",
    category: "Casual / Lifestyle",
    price: "R$ 299,00",
    sizes: ["40", "41", "42"],
    badgeMain: "Oferta -15% OFF",
    badgeSecondary: "Poucas unidades",
    description:
      "Silhueta clean, toda preta, perfeita para usar tanto no rolê quanto no dia a dia, com acabamento em camurça e sola vulcanizada.",
    highlights: [
      "Visual todo preto fácil de combinar",
      "Acabamento em camurça",
      "Ideal para quem gosta de estética mais discreta",
      "Confortável para uso diário"
    ],
    mainImageLabel: "FOTO PRINCIPAL CAMPUS ALL BLACK",
    thumbs: ["Lateral", "Traseira", "Solado", "Detalhe"],
    whatsappText:
      "Ol%C3%A1,%20tenho%20interesse%20no%20Adidas%20Campus%20All%20Black.%20Tem%20no%20tamanho%2040%2F41%3F"
  },

  "nb-9060-grey-pink": {
    slug: "nb-9060-grey-pink",
    name: "NB 9060 Grey Pink",
    brand: "New Balance",
    gender: "Feminino",
    category: "Casual / Lifestyle",
    price: "R$ 419,00",
    sizes: ["34", "35", "36", "37"],
    badgeMain: "Poucas unidades",
    badgeSecondary: "Super confortável",
    description:
      "Combinação de cinza com detalhes em rosa, sola robusta e extremamente confortável para quem passa o dia inteiro na rua.",
    highlights: [
      "Colorway cinza com detalhes rosa",
      "Sola robusta e macia",
      "Visual moderno e diferenciado",
      "Perfeito para looks urbanos"
    ],
    mainImageLabel: "FOTO PRINCIPAL NB 9060 GREY PINK",
    thumbs: ["Lateral", "Traseira", "Solado", "Detalhe"],
    whatsappText:
      "Ol%C3%A1,%20tenho%20interesse%20no%20NB%209060%20Grey%20Pink.%20Voc%C3%AAs%20t%C3%AAm%20no%20tamanho%2036%3F"
  }
};

// Função utilitária para montar link de WhatsApp
function buildWhatsAppUrl(encodedText) {
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodedText}`;
}
